<?php
/**
 * @file
 * Contains theme and help hooks for the TARDIS module.
 */

 use Drupal\Core\Routing\RouteMatchInterface;
/**
 * Implements hook_theme().
 */
function s3_gallery_theme($existing, $type, $theme, $path) {
  return [
    // ... your existing hooks ...
    'gallery_home' => [
      'variables' => ['years' => NULL],
    ],
    'album' => [
      'variables' => ['images' => NULL],
    ],
    // ADD THIS NEW ONE:
    'gallery-block' => [
      'variables' => ['albums' => NULL],
    ],
  ];
}

if (\Drupal::hasContainer()) {
    \Drupal::moduleHandler()->loadInclude('s3_gallery', 'inc', 's3_gallery.theme');
}
